name: faktisk
description: Faktisk.no - The application.

dependencies:
  test: any
  http: ^0.12.0+2
  html: ^0.14.0+2
  flutter_staggered_grid_view: ^0.2.7
  url_launcher: ^5.0.2

  built_collection: ^4.2.1
  built_value: ^6.5.0

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  adaptive_icon_background: "assets/icons/app_icon.png"
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

# If ios Icon is too small, replace icon with 512 resolution icon instead of 1024

dev_dependencies:
  build_runner: any
  built_value_generator: ^6.5.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true